# Generated by Django 2.2.5 on 2019-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_member_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='last_read_message_id',
            new_name='last_read_message',
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.IntegerField(blank=True, verbose_name='Новые сообщения'),
        ),
    ]
