# Generated by Django 2.2.5 on 2019-11-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20191118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mymessages.Message', verbose_name='Последнее прочитанное сообщение'),
        ),
    ]
