# Generated by Django 2.2.5 on 2019-11-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191118_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='mymessages.Message', verbose_name='Последнее сообщение'),
        ),
    ]
