# Generated by Django 2.2.5 on 2019-11-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20191119_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
