# Generated by Django 2.2.5 on 2019-11-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0005_auto_20191112_2324'),
        ('chats', '0009_remove_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_last_message', to='mymessages.Message', verbose_name='Последнее сообщение'),
        ),
    ]
