# Generated by Django 2.2.5 on 2019-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
