# Generated by Django 2.2.5 on 2019-12-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_chat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Аватар чата'),
        ),
    ]
