# Generated by Django 2.2.5 on 2019-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attachment', models.CharField(blank=True, max_length=32, verbose_name='Тип вложения')),
                ('url', models.CharField(blank=True, max_length=32, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
