# Generated by Django 2.2.5 on 2019-11-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_auto_20191112_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='key',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ключ'),
        ),
    ]
