# Generated by Django 2.2.5 on 2019-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0011_auto_20191127_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='key',
            field=models.TextField(blank=True, verbose_name='Ключ'),
        ),
    ]
