# Generated by Django 2.2.5 on 2019-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
