# Generated by Django 2.2.5 on 2019-11-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0003_auto_20191106_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-added_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
