# Generated by Django 2.2.5 on 2019-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0005_auto_20191112_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
