# Generated by Django 2.2.5 on 2019-11-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0006_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
