"""
Django settings for messenger project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from application.myconfig import DefaultDatabase as DD
from application.myconfig import secret_key
from application.myconfig import FaceBook
from application.myconfig import Odnoklassniki
from application.myconfig import GitHub
from application.myconfig import S3_Storage

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# LOGIN_URL = 'login'
LOGIN_URL = 'http://127.0.0.1:3000/'
# LOGIN_REDIRECT_URL = "home"
LOGIN_REDIRECT_URL = 'http://127.0.0.1:3000/chats'
LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'login'
LOGOUT_REDIRECT_URL = 'http://127.0.0.1:3000/'

SOCIAL_AUTH_FACEBOOK_KEY = FaceBook.social_auth_facebook_key  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = FaceBook.social_auth_facebook_secret  # App Secret
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'locale': 'ru_RU',
    'fields': 'id, name, email, age_range'
}

# SOCIAL_AUTH_VK_OAUTH2_KEY = ''
# SOCIAL_AUTH_VK_OAUTH2_SECRET = ''
# # SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']

SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_KEY = Odnoklassniki.social_auth_odnoklassniki_oauth2_key
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_SECRET = Odnoklassniki.social_auth_odnoklassniki_oauth2_secret
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_PUBLIC_NAME = Odnoklassniki.social_auth_odnoklassniki_oauth2_public_name

SOCIAL_AUTH_GITHUB_KEY = GitHub.social_auth_github_key
SOCIAL_AUTH_GITHUB_SECRET = GitHub.social_auth_github_secret
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_profile',
    'chats',
    'messages',
    'attachments',
    'social_django',
    'sslserver',
    'corsheaders',
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.linkedin.LinkedinOAuth2',
    'social_core.backends.instagram.InstagramOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    # 'social_core.backends.vk.VKOAuth2',
    'social_core.backends.odnoklassniki.OdnoklassnikiOAuth2',
    'social_core.backends.github.GithubOAuth2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DD.database_name,  # 'messenger_user_db',
        'USER': DD.database_user,  # 'messenger_user',
        'PASSWORD': DD.database_password,  # '12345',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_ENDPOINT_URL = S3_Storage.aws_s3_endpoint_url
AWS_ACCESS_KEY_ID = S3_Storage.aws_access_key_id
AWS_SECRET_ACCESS_KEY = S3_Storage.aws_secret_access_key
AWS_STORAGE_BUCKET_NAME = S3_Storage.aws_storage_bucket_name

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_ROOT = '/Users/maksim/Desktop/FullStack/Backend/Лекции/Лекция-1/Git/Project/' \
             '2019-2-Atom-Backend-M-Makarov/homework-4/messenger/media/'

try:
    from .local_settings import *
except ImportError:
    pass

AUTH_USER_MODEL = "user_profile.UserProfile"

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = ('http://127.0.0.1:3000', 'https://127.0.0.1:8000')
